### ISSUE TITLE
More examples needed

### ISSUE THREAD

**Issue by pmario** [kixam/TW5-visjsTimeline#1]
Nice plugin. Well done!

IMO from the help text alone, you don't get the possibilities.

**Comment by kixam** [comment]
Thank you for your comment.

Actually, you get most of them... maybe it is even confusing because this one example shows too many features at once.

I will look into improving the demo site, but at the moment, you get everything on a (PC) screen, and I fear if I add more examples I will have to structure the site a lot, and information will get diffused.

If you feel like making a better demo site yourself, I would be glad to use it on the website however, and keep feeding it from then as I add features.

**Comment by kixam** [comment]
improved (enough?) by ddd10a6c781a508fce44d7ae9ead8ec13106f9eb
