### ISSUE TITLE
i18n config

### ISSUE THREAD

**Issue by silvyn** [kixam/TW5-visjsTimeline#10]
Hello @kixam, I'm wondering how to configure i18n to configure TW5-visjsTimeline in French.

I have a quick look on http://momentjs.com/docs/#/i18n/ but I don't really know how to..

Thanks for your help.

**Comment by silvyn** [comment]
Well, I just add French TW plugin, and my timeline is in French.. So I think I can close this thread ?

**Comment by kixam** [comment]
Yes, this feature was added in v0.7.2 :)

**Comment by kixam** [comment]
hi @felixhayashi, I remember you were interested in localization, but maybe you did not see this thread, because I expected a comment from you on this ;)

I implemented implicit locale support from moment.js, based on selected language on TW5. Indeed, regarding date and time, it is not simply about translation of words: formats (grammar) has to be taken into account as well.

There are 2 limitations:
- despite moment.js was translated in a lot more languages and variants than TW5, I did not find some of the TW5 languages/variants in moment.js database (namely pa-IN, ia-IA, and de-AT);
- two vis.js internal strings are not translated, because they are not provided by moment.js and I did not want to try Google translation or such on these... I mean, if vis.js guys did not do it, I am no wiser.

Anyway, I do not think this method can be used on Network

**Comment by felixhayashi** [comment]
> I implemented implicit locale support from moment.js, based on selected language on TW5.

That is a great idea. I can do the same for the network module, its possible there as well. But the problem is I have many tw-dialogs that are not translated. I'll wait another year with adding translation-features to tiddlymap :)

> I did not find some of the TW5 languages/variants in moment.js database (namely pa-IN, ia-IA, and de-AT);

austrians (de-AT) should be able to understand normal german (de-DE) :D Maybe if a locale doesn't match a tw-locale just use english as fallback...

**Comment by kixam** [comment]
> Maybe if a locale doesn't match a tw-locale just use english as fallback...

This is what happens already

> austrians (de-AT) should be able to understand normal german (de-DE)

Actually, if you select de-AT in TW5, the plugin should display German dates ;) it is because I implemented the feature in a lazy way :p

**Comment by felixhayashi** [comment]
> Actually, if you select de-AT in TW5, the plugin should display German dates ;) it is because I implemented the feature in a lazy way :p

You mean only parsing the first two letters of the locale? I would have done the same... who cares about dialects :)

**Comment by kixam** [comment]
the only exception to this is Chinese, because it seems to me there is a big difference (visually at least), but yes ;)
