### ISSUE TITLE
Button to Sort/Filter by Tag or Name?

### ISSUE THREAD

**Issue by UXlibrarian** [kixam/TW5-visjsTimeline#21]
Hello! 

Thank you for continuing the work of this plugin. I've spent _a lot_ of time and money searching for the best timeline software to suit my needs. This plugin is like 90% of the way there. 

Do you know if it is possible to create a sortable/filterable view? For instance, on my timeline, I have five different groups (American, Spaniard, English, etc.) which are tags. In each tag, I have people who belong to each (e.g. Alexander Hamilton is tagged American). I have all these people in one timeline so that I can see who their contemporaries are across various nationalities. However, it can be hard to do this when there may be 10 people born within a two year period. Lots of scrolling up and down to try and see everyone, if that makes sense? 

What would be nice is to be able to select "See only Americans and English" or "View only Hamilton and Franklin" to view on the timeline at any one time. Thoughts?

**Comment by kixam** [comment]
Hi @UXlibrarian ,

Thank you for using this plugin, it helps to know that your work is also useful to other people. Also, it is good to have feedback regarding different use cases.

Regarding your question, I actually did something that might cover your need for my own use case. I added check boxes on top of the calendar that builds a dynamic filter for it. I did not try to use a text input field but I guess this could be done as well. Here goes.

I put my calendar in its own tiddler named `Calendar`, which is something like the following (I tried to adapt to your needs for faster integration):

```
<!-- build a nice overlay -->
<div style="position:relative;">
<div style="position:absolute;top:2px;left:2px;z-index:999;padding-top:2px;padding-left:10px;padding-right:10px;background-color:rgba(100,200,100,.1);border-radius:25px;box-shadow:1px 1px 2px">

<!-- add as many checkboxes as needed, using fields from the 'Calendar' tiddler. The 'checked' value is the name of the tag of which you want tiddlers to be displayed; the 'unchecked' value is the empty string. The name of the field is not important but it is better for clarity to use the same as the tag if possible. -->
<$checkbox tiddler=Calendar field=American checked="American" unchecked=""> American</$checkbox>
<$checkbox tiddler=Calendar field=Spaniard checked="Spaniard" unchecked=""> Spaniard</$checkbox>
<$checkbox tiddler=Calendar field=English checked="English" unchecked=""> English</$checkbox>
</div>

<!-- display the calendar using a dynamic filter -->
<$visjstimeline filter="[tag{Calendar!!American}] [tag{Calendar!!Spaniard}] [tag{Calendar!!English}]" groupTags="American Spaniard English"/>

</div>
```

Does it fit your need ?

**Comment by UXlibrarian** [comment]
Hello! 

_Thank you._ I appreciate your time very much. I was praising your plugin over on Twitter earlier, so I hope you have more people showing up to use it. :-) 

I copied the code you gave me into a new tiddler (w/o choosing content type). When I click on the checkboxes, I see the Calendar tiddler jump/refresh every time I click a checkbox. Yet nothing changes. The new tiddler which has your code in it doesn't react at all to the checkboxes being selected. I also tried a few other content types (HTML and TiddlyWiki5) with the exact same results. 

I did notice that on the original Calendar tiddler, new fields appear which read like so: 
- American:American
- Spaniard:Spaniard
- English:English 

When I deleted those auto-generated fields off the original Calendar tiddler, the "Calendar with Filter" tiddler (which uses your code) has all the fields disappear. So I went back to Calendar and recreated them. No dice. The "Calendar with Filter" tiddler has still lost the display of people on its timeline. 

Next, I click on the checkboxes on "Calendar with Filter" after reassigning the custom fields for Calendar. When I check on Calendar now, the custom field values have emptied out again. Hmmm...!

**Comment by kixam** [comment]
Hi,

My code was designed to be implemented in the same tiddler that it is supposed to affect. That means you are not supposed to put it in a tiddler named "Calendar with Filter" , because as it is, it is reading and writing from/to fields of the tiddler named "Calendar" (like you could observe yourself). Also, the trick is when fields change values, the tiddler to which they belong gets refreshed, so if it embeds a calendar, it gets refreshed as well, at which time it takes into account its modified filter. Please read the comments I put in the code, and change the variable values as needed.

Note that, if you manually remove or change the fields values, the filter would be affected, just like it would if you would un/check the check boxes and their values were changed by script. Unchecking a box actually resets the corresponding field value to the empty string, which in turn "filters out" the corresponding tag from the calendar.

Also, if all the fields are empty or non-existent, or actually if they have a value that does not correspond to any relevant tag, the calendar filter should prevent any entry to be displayed in the calendar.

If you do not change anything to what you have done so far, you can check it is partially working by closing and reopening the "Calendar with Filter" tiddler after you un/check a box, and see that the displayed entries have changed accordingly.

**Comment by UXlibrarian** [comment]
This time I put your code into my one tiddler and it worked like a charm. It's like magic! For anyone who reads this later, I had these fields in my person tiddlers: born, died. This way you see a true timeline of their life length. Which in my final code looks like this:

<$visjstimeline startDateField="born" endDateField="died" format="YYYY"  filter="[tag{Calendar!!American}] [tag{Calendar!!Spaniard}] [tag{Calendar!!English}]" groupTags="American Spaniard English"/>

If I figure out how to get a search box option working too, I'll post back here. Thank you so much. 

Follow-up note: I just realized that only three checkboxes may be selected at once. If you select a fourth, it'll unselect the previous one.

**Comment by kixam** [comment]
> If I figure out how to get a search box option working too, I'll post back here. Thank you so much.

Thank you.

> Follow-up note: I just realized that only three checkboxes may be selected at once. If you select a fourth, it'll unselect the previous one.

I have 5 checkboxes on mine and everything works as expected... do your fields have different names? did you change the checkboxes code and the calendar (`<$visjstimeline .. />`) code, in unison?

**Comment by UXlibrarian** [comment]
Annnnnnd I'm an idiot. I copied the last checkbox multiple more times and forgot to change English to the other terms. I got the label name changed, but not the interior.
